"""Add education and experience

Revision ID: adc2a8a32b74
Revises: e650f38bb16b
Create Date: 2026-03-31 15:59:58.172770

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'adc2a8a32b74'
down_revision: Union[str, Sequence[str], None] = 'e650f38bb16b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('students', sa.Column('education', sa.String(), nullable=True))
    op.add_column('students', sa.Column('experience', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('students', 'experience')
    op.drop_column('students', 'education')
    # ### end Alembic commands ###
